#!/bin/bash

rm -f sc sc.tab.c

bison sc.y

if [ $? == 0 ]
then
	gcc -o sc -O3 -lm -Wall sc.tab.c matrix.c reverse_polish.c stack.c symbol_table.c codegen.c functions.c variables.c
else
	echo "Errors ocurred while running bison on sc.y.. Exiting."
	exit 1
fi

